version: 2

sources:
  - name: spotify_dataset                     # Group name for all raw data sources
    schema: spotify_dataset      # Your BigQuery dataset name
    database: spotify-project-457217  # Your GCP project ID
    meta:
      location: "EU"
    
    tables:
      - name: spotify_songs           # Must match your actual BigQuery table name
        description: "Raw Spotify tracks data loaded from Paquet"
        
        # Optional: Add column tests
        columns:
          - name: track_id
            tests:
              - not_null
              - unique
          - name: popularity
            tests:
              - not_null